In [1]:
import pandas as pd 
import numpy as np 
import os 
assets_dir = f"{os.getcwd()}/assets"

results_dir= os.path.join(assets_dir, "results/global_results")

In [2]:
one_global = [] 
for file in os.listdir(results_dir): 
    print(file)
    if file.endswith('.csv'): 
        file_path = os.path.join(results_dir, file)
        df = pd.read_csv(file_path)
        one_global.append(df) 

one_global = pd.concat(one_global) 
one_global.to_csv(os.path.join(results_dir, 'global_results.csv'), index=False)

global_results_8d0a5491-49d5-476a-ad79-340b3f9c5bde.csv
global_results_8b4f98ec-4022-47ab-9593-130bf2d9b593.csv:Zone.Identifier
global_results_12c8ca99-f610-47bd-a8a5-10370c3ccd7f.csv:Zone.Identifier
global_results_0f3c552f-f39d-4e84-9598-83e00a379e81.csv
global_results_dfd9c56a-d2e2-494a-90a7-a168d3ee91c6.csv:Zone.Identifier
global_results_ccab394b-7960-47f4-b4f3-96c15b8f9ade.csv
global_results_781f59e1-c060-46eb-97df-0b2bb5315b10.csv
global_results_e2476302-167b-4bb1-a151-1ab43424b84e.csv
global_results_fa3c7d1c-7c93-4858-9846-de570f66de10.csv:Zone.Identifier
global_results_163785b0-6dab-41d5-aaed-342de76399ed.csv:Zone.Identifier
global_results_030f60aa-9379-4040-be01-cfe11cc7cce0.csv:Zone.Identifier
global_results_12c8ca99-f610-47bd-a8a5-10370c3ccd7f.csv
global_results_4854186a-3c43-48d3-a096-80c21a988d3f.csv:Zone.Identifier
global_results_a9d2de3d-37c2-4e31-9a96-0d4bfd48b0af.csv
global_results_e432c52d-2fe1-420e-a37b-dfb88dee0bf1.csv
global_results_38b2fac7-268a-4734-9b07-7402099885af.csv
global_results_4b3dcc83-beef-4829-8700-e7b7c607ea91.csv
global_results_b472af99-bf29-48df-af79-9aea945a8914.csv
global_results_ef0fd91e-f427-4b4e-ae82-888f05f985af.csv:Zone.Identifier
global_results_3dd9f2d7-032a-49aa-b62a-4c18b16ed870.csv
global_results_1bb2a6d2-8abb-4176-bd1b-fa66d83c3a45.csv:Zone.Identifier
global_results_09db9e0c-159f-4e5e-a43a-19c58ab713d7.csv
global_results_f3e61c45-d84f-4881-9240-52056c282539.csv
global_results_3b2c372c-ae8b-42e3-b000-3494acb45fa6.csv:Zone.Identifier
global_results_ea72157d-c603-454e-a4d0-e18dbff5d5cf.csv
global_results_a7958d11-3be8-4128-b608-153256651663.csv
global_results_1bb2a6d2-8abb-4176-bd1b-fa66d83c3a45.csv
global_results_80587dcc-e274-4c8a-885c-a1d0f68f3589.csv
global_results_c598d2cd-9b4a-4509-869e-618a8fa39ffa.csv
global_results_a67ab224-a0a6-4341-b363-53f08754dce6.csv
global_results_9e7b4c6a-f046-4cf0-a00c-f2977e7559ee.csv:Zone.Identifier
global_results_c468d6c3-79a7-433b-b8bc-a5b4a1e4268a.csv
global_results_df4837cc-e5d0-4c0b-a098-5fb09e9d1571.csv:Zone.Identifier
global_results_fe286749-3592-4f82-9613-72f34cc51a3c.csv
global_results_ad8d5e4a-24a9-4900-aced-cbab67be2864.csv
global_results_30104ce0-cebf-4c71-a154-4b858ce57214.csv
global_results_cc2a2f83-01b8-4ebe-8dd5-2a2c8c1e7c27.csv:Zone.Identifier
global_results_1e56e154-8ab1-4ddc-aacd-b7542e02d863.csv:Zone.Identifier
global_results_de609f8d-5249-4a3e-8848-753c16083f3a.csv
global_results_0be221cb-69bf-4410-a2b0-15951dfcc5af.csv
global_results_a1977de9-d50d-4945-8ae3-e681631fc8f4.csv
global_results_5f65d0b0-d056-4513-94fe-4d22ecd32ea8.csv
global_results_d2409c69-58ba-41d8-ace6-449f37bc952c.csv
global_results_f916c1f1-0220-4897-8927-40b8062441a2.csv
global_results_bd25c460-0b40-4972-a04e-03b767c59256.csv:Zone.Identifier
global_results_b3ed4135-5841-42fe-acc0-e9acdaf10f37.csv
global_results_fdd377bb-9d4b-46b9-8f35-59fb47ecbaee.csv:Zone.Identifier
global_results_ccbae0e5-0131-4859-9266-ac6f107f7123.csv
global_results_c468d6c3-79a7-433b-b8bc-a5b4a1e4268a.csv:Zone.Identifier
global_results_fdd377bb-9d4b-46b9-8f35-59fb47ecbaee.csv
global_results_782218d0-9919-4328-8c76-03528fb9ae5b.csv:Zone.Identifier
global_results_ad8d5e4a-24a9-4900-aced-cbab67be2864.csv:Zone.Identifier
global_results_1e56e154-8ab1-4ddc-aacd-b7542e02d863.csv
global_results_4ecd6cca-dbc0-4ef4-af89-d6f03f291d84.csv:Zone.Identifier
global_results_5b86cac7-8a00-4647-b801-75bf03f5a9cc.csv:Zone.Identifier
global_results_a081ba31-f754-44b9-8762-c2d88ec1e478.csv:Zone.Identifier
global_results_0be221cb-69bf-4410-a2b0-15951dfcc5af.csv:Zone.Identifier
global_results_96c4e728-04be-40de-83bb-80766171ed24.csv
global_results_a9aafff7-5a1e-4f38-a6b9-e1dad8cc6d66.csv
global_results_ca581bbb-78bc-42d1-91d1-582cc185502c.csv:Zone.Identifier
global_results_96cdbf11-ffb3-4bab-9c15-d3530cff09dc.csv:Zone.Identifier
global_results_9cf366cf-2a69-42a0-b2d0-f28b00c2e6ee.csv
global_results_b83b0b70-b222-46eb-b52a-65f0d39c5831.csv
global_results_3dd9f2d7-032a-49aa-b62a-4c18b16ed870.csv:Zone.Identifier
global_results_782218d0-9919-4328-8c76-03528fb9ae5b.csv
global_results_a67ab224-a0a6-4341-b363-53f08754dce6.csv:Zone.Identifier
global_results_8b4f98ec-4022-47ab-9593-130bf2d9b593.csv
global_results_04abb547-3074-4b17-a4da-69d7e89cb218.csv
global_results_346c4cae-bd6b-4df3-bab4-5a286d326c0c.csv
global_results_9da61681-cebf-4d49-b9d1-b1c82c95da2f.csv:Zone.Identifier
global_results_f5e2f9cb-1c14-4d58-9bec-2aa6b4b51f57.csv
global_results_3f3ad5f0-9cbe-4707-acb8-13cb4605ea50.csv
global_results_b1b2ca38-86dc-4f56-af50-cc92e9ed3d20.csv:Zone.Identifier
global_results_1a1ca3a7-1daa-4ae9-8a94-bcb67c7f6642.csv:Zone.Identifier
global_results_e2ae19a0-bed9-4156-af87-9b057dd28bee.csv
global_results_2a754639-8bbd-4993-8568-a8e8b90068b0.csv
global_results_5226db46-989a-4eba-9ec8-14b6927efcdf.csv
global_results_2a3d4b73-848e-4e2b-9f59-8ad3bd0b10ee.csv
global_results_5aae3e69-df9e-43bf-bf9d-92000daec9cf.csv:Zone.Identifier
global_results_3ed50e9a-7769-409a-8bcc-ae5dbe7dda36.csv
global_results_1aca5522-a3e4-4594-984b-45bacfbab960.csv
global_results_f9936d4f-1e0e-47fb-ac81-1d3b619aa53d.csv
global_results_441d72fb-3619-4b31-952d-5b5dbd21c742.csv
global_results_0871499d-bc9a-45fa-89c6-9f6b54607ec7.csv
global_results_efce4a83-6faa-4cbd-ad71-9ef417600cf7.csv
global_results_23abbf06-db98-445f-9f55-fb84454ce6b9.csv
global_results_b32a0a9d-c643-4c50-8840-370a58747db2.csv
global_results_030f60aa-9379-4040-be01-cfe11cc7cce0.csv
global_results_f7f6ab7e-a9f9-44e7-b7d3-0b6338e3b19a.csv
global_results_cfd1120b-9344-42d5-a887-bb2305d6f49e.csv
global_results_27dad9d9-bcee-46a9-993c-4dd5d6462d68.csv
global_results_152b194b-8bf2-4ff4-a840-fb92f518f8a8.csv
global_results_80587dcc-e274-4c8a-885c-a1d0f68f3589.csv:Zone.Identifier
global_results_ef0fd91e-f427-4b4e-ae82-888f05f985af.csv
global_results_ac51957b-4141-414a-b41f-6350fdddc0db.csv
global_results_e1027186-8021-42b6-8d55-4cd896058bca.csv:Zone.Identifier
global_results_821fc49e-7c60-4a66-a084-c47c96019ee2.csv:Zone.Identifier
global_results_e9cef224-5215-4908-9542-57d2e4716a51.csv
global_results_1350196e-3159-4eb3-9092-33c442c14518.csv:Zone.Identifier
global_results_9f8630c0-9985-4797-8749-8d4c6711ca8e.csv
global_results_0b2b5901-92cd-44fa-8de7-5c38fc5de7d4.csv:Zone.Identifier
global_results_4b4ab22c-19ff-4952-9ee5-f614a3da20de.csv:Zone.Identifier
global_results_e4068ff6-c2a3-4202-b5b1-ca6752d5498b.csv:Zone.Identifier
global_results_8c2b2bf8-a7c4-42e7-bcfb-d073c69de5d2.csv:Zone.Identifier
global_results_9bc5e1b5-af7b-4c76-ae44-a1e2272fee00.csv
global_results_b472af99-bf29-48df-af79-9aea945a8914.csv:Zone.Identifier
global_results_346c4cae-bd6b-4df3-bab4-5a286d326c0c.csv:Zone.Identifier
global_results_93b0f375-7203-4a14-a585-d61c7c420de1.csv
global_results_e9cef224-5215-4908-9542-57d2e4716a51.csv:Zone.Identifier
global_results_a571196d-6e21-42e2-8f2c-6444372768f2.csv:Zone.Identifier
global_results_2f47138c-cc83-4810-86c9-105e2333ff8d.csv:Zone.Identifier
global_results_f74c5b4c-c9ea-4845-a551-e3f50d62125b.csv:Zone.Identifier
global_results_5b86cac7-8a00-4647-b801-75bf03f5a9cc.csv
global_results_e7bdab7f-1bf1-4102-95d2-2d3df7e299e2.csv
global_results_cc2a2f83-01b8-4ebe-8dd5-2a2c8c1e7c27.csv
global_results_1fcd9a52-3003-4e0d-a4d8-6ef22c2de376.csv
global_results_206c18ad-242a-4113-8889-5b8c88fbce36.csv
global_results_13c47666-d0bc-4307-b204-40315eb85232.csv
global_results_200577e2-8eda-4f1a-ab5f-1a9d4397e652.csv:Zone.Identifier
global_results_b83b0b70-b222-46eb-b52a-65f0d39c5831.csv:Zone.Identifier
global_results_78972c86-d5fb-4e2b-b447-d6097d149757.csv
global_results_a25b8a2b-d336-4ea9-bf95-e81040ab131f.csv
global_results_a571196d-6e21-42e2-8f2c-6444372768f2.csv
global_results_a9d2de3d-37c2-4e31-9a96-0d4bfd48b0af.csv:Zone.Identifier
global_results_117442ca-df67-4d8a-8003-0ac2b178b4c8.csv:Zone.Identifier
global_results_bb0f14c7-f27d-4905-b832-9a45ca9fd012.csv:Zone.Identifier
global_results_db796356-536c-4c66-b64d-0d72e70ec17e.csv
global_results_4854186a-3c43-48d3-a096-80c21a988d3f.csv
global_results_1b1404a6-08ec-4c1d-89f8-3fdb9f427791.csv
global_results_aaadc103-181e-429b-a513-1ecaf6905208.csv
global_results_b32a0a9d-c643-4c50-8840-370a58747db2.csv:Zone.Identifier
global_results_781f59e1-c060-46eb-97df-0b2bb5315b10.csv:Zone.Identifier
global_results_4b3dcc83-beef-4829-8700-e7b7c607ea91.csv:Zone.Identifier
global_results_0b2b5901-92cd-44fa-8de7-5c38fc5de7d4.csv
global_results_e7f4925b-8a4f-4ed1-ab46-6d7179f42103.csv
global_results_e865650c-d656-4134-934b-fdf76245b48c.csv:Zone.Identifier
global_results_f916c1f1-0220-4897-8927-40b8062441a2.csv:Zone.Identifier
global_results_e9e5b227-6674-48cf-b14d-fde02bf8858a.csv:Zone.Identifier
global_results_efce4a83-6faa-4cbd-ad71-9ef417600cf7.csv:Zone.Identifier
global_results_ee52092e-6949-478e-8ac0-83aa37f0f207.csv:Zone.Identifier
global_results_385d7bad-1b6a-47d1-97fa-a78eef3ab7f2.csv
global_results_ccbae0e5-0131-4859-9266-ac6f107f7123.csv:Zone.Identifier
global_results_78d18bb9-da93-432d-b113-74f5554dc2e5.csv:Zone.Identifier
global_results_b175ad43-4ea7-41e0-8e4d-900fcd47a57f.csv
global_results_dba5bac7-b394-4368-b76a-4b43fac04c6a.csv:Zone.Identifier
global_results_32df208a-5711-4274-bcd0-45cab83dae68.csv
global_results_7cde7765-7af2-4f81-b63d-d3d8bb948d63.csv:Zone.Identifier
global_results_fa3c7d1c-7c93-4858-9846-de570f66de10.csv
global_results_2a260836-1a1d-465b-96f8-096680465ed9.csv
global_results_2b86d6f8-971d-4c98-8dab-32f5cb3465c4.csv:Zone.Identifier
global_results_e5dae88c-a9f1-45ab-ba5f-6e20a3916939.csv:Zone.Identifier
global_results_174156dd-495c-48c0-b3ed-5d18edd6e66e.csv:Zone.Identifier
global_results_449887af-cd53-464a-9ae3-e0afc5a99f1e.csv:Zone.Identifier
global_results_84651058-c284-46ac-8ee7-8f296d38395f.csv:Zone.Identifier
global_results_821fc49e-7c60-4a66-a084-c47c96019ee2.csv
global_results_3f5f96a5-1767-46c2-bde0-5be3b96cfb0a.csv
global_results_1a1ca3a7-1daa-4ae9-8a94-bcb67c7f6642.csv
global_results_e9e5b227-6674-48cf-b14d-fde02bf8858a.csv
global_results_5aae3e69-df9e-43bf-bf9d-92000daec9cf.csv
global_results_20bc2b79-b3a5-4f9d-a76e-22dab453e2a3.csv:Zone.Identifier
global_results_8a61e11f-d91a-4b12-928d-d86c6956871e.csv
global_results_e1027186-8021-42b6-8d55-4cd896058bca.csv
global_results_f5e2f9cb-1c14-4d58-9bec-2aa6b4b51f57.csv:Zone.Identifier
global_results_6ed4f24a-6189-4f2a-9145-c3d4845dc78c.csv
global_results_5ea2cc12-2c76-4a78-9b31-ec02e604ce3a.csv
global_results_ae4bede6-b7a3-40df-8032-680e998e0b55.csv
global_results_32df208a-5711-4274-bcd0-45cab83dae68.csv:Zone.Identifier
global_results_ccab394b-7960-47f4-b4f3-96c15b8f9ade.csv:Zone.Identifier
global_results_1dd8cf5f-7137-438f-a3a0-cf805098a23f.csv
global_results_b01b3472-f17a-45db-84ac-42afa77446b7.csv
global_results_b3ed4135-5841-42fe-acc0-e9acdaf10f37.csv:Zone.Identifier
global_results_1b1404a6-08ec-4c1d-89f8-3fdb9f427791.csv:Zone.Identifier
global_results_48af7093-0a52-4a82-b542-b568efb83c12.csv:Zone.Identifier
global_results_e5dae88c-a9f1-45ab-ba5f-6e20a3916939.csv
global_results_19d504bb-2ae0-4d62-a9d1-87b64d86f857.csv:Zone.Identifier
global_results_4ecd6cca-dbc0-4ef4-af89-d6f03f291d84.csv
global_results_739c5b8f-8f1b-4fd4-b60c-5bc8e0197712.csv
global_results_528f8855-1f22-4988-92e7-9a8f253f104a.csv:Zone.Identifier
global_results_441d72fb-3619-4b31-952d-5b5dbd21c742.csv:Zone.Identifier
global_results_27dad9d9-bcee-46a9-993c-4dd5d6462d68.csv:Zone.Identifier
global_results_4ded8b7e-df5f-4061-9648-3189d5d31698.csv:Zone.Identifier
global_results_df4837cc-e5d0-4c0b-a098-5fb09e9d1571.csv
global_results_8148542c-4883-4349-a307-72c11475ad89.csv
global_results_d2409c69-58ba-41d8-ace6-449f37bc952c.csv:Zone.Identifier
global_results_ea88138f-9049-4b5b-b820-18f6b23dfc48.csv:Zone.Identifier
global_results_e7f4925b-8a4f-4ed1-ab46-6d7179f42103.csv:Zone.Identifier
global_results_167e58d9-57a7-444d-af88-f98157984137.csv:Zone.Identifier
global_results_73d46ae3-2f5c-4893-b77e-e34c1c23159d.csv
global_results_efe48adf-f007-4097-bcf8-35734b6449a1.csv:Zone.Identifier
global_results_0f5148b5-0818-48e8-847b-2a2e9c8ea75b.csv:Zone.Identifier
global_results_d79b1649-2e9a-4c85-b8d9-f50a54557e69.csv
global_results_3ed50e9a-7769-409a-8bcc-ae5dbe7dda36.csv:Zone.Identifier
global_results_a5144d0b-4a58-4d67-a77a-af2112a86b5c.csv:Zone.Identifier
global_results_3450646a-37f6-4575-8a22-2ad4a8791bd2.csv
global_results_d477e504-1ddf-4393-adde-b79b27d8fbec.csv
global_results_2a754639-8bbd-4993-8568-a8e8b90068b0.csv:Zone.Identifier
global_results_0cf5f4b5-5a04-4934-b715-d7b62bae6e66.csv
global_results_1aca5522-a3e4-4594-984b-45bacfbab960.csv:Zone.Identifier
global_results_8148542c-4883-4349-a307-72c11475ad89.csv:Zone.Identifier
global_results_7cde7765-7af2-4f81-b63d-d3d8bb948d63.csv
global_results_8c3a8560-c903-4906-afdf-f024d2039ac4.csv
global_results_a5144d0b-4a58-4d67-a77a-af2112a86b5c.csv
global_results_378ebb6f-f77d-41e0-9f78-5455b8f0efde.csv:Zone.Identifier
global_results_8d0a5491-49d5-476a-ad79-340b3f9c5bde.csv:Zone.Identifier
global_results_2152ed9c-06ec-432a-a254-251bb06646dd.csv:Zone.Identifier
global_results_e865650c-d656-4134-934b-fdf76245b48c.csv
global_results_5ea2cc12-2c76-4a78-9b31-ec02e604ce3a.csv:Zone.Identifier
global_results_d477e504-1ddf-4393-adde-b79b27d8fbec.csv:Zone.Identifier
global_results_87e6eaa8-3682-4ae6-b8f1-2c7271c85dc3.csv
global_results_2a3d4b73-848e-4e2b-9f59-8ad3bd0b10ee.csv:Zone.Identifier
global_results_dfd9c56a-d2e2-494a-90a7-a168d3ee91c6.csv
global_results_4d208d81-47f5-474f-ae55-b205e8ccfff0.csv:Zone.Identifier
global_results_385d7bad-1b6a-47d1-97fa-a78eef3ab7f2.csv:Zone.Identifier
global_results_9bf205ff-db14-4ed1-a27c-c2282aa714db.csv:Zone.Identifier
global_results_1dd8cf5f-7137-438f-a3a0-cf805098a23f.csv:Zone.Identifier
global_results_ac51957b-4141-414a-b41f-6350fdddc0db.csv:Zone.Identifier
global_results_a805b2f6-84c5-482b-a554-0c2e56da7e92.csv:Zone.Identifier
global_results_a805b2f6-84c5-482b-a554-0c2e56da7e92.csv
global_results_3450646a-37f6-4575-8a22-2ad4a8791bd2.csv:Zone.Identifier
global_results_167e58d9-57a7-444d-af88-f98157984137.csv
global_results_6e0a4180-dc65-4c43-9937-ac4466b5c6bb.csv:Zone.Identifier
global_results_efe48adf-f007-4097-bcf8-35734b6449a1.csv
global_results_2b86d6f8-971d-4c98-8dab-32f5cb3465c4.csv
global_results_e2ad7534-a2ff-4373-880c-b02469ef671c.csv
global_results_5114f8f1-0793-4225-89d0-04f58b49668b.csv:Zone.Identifier
global_results_d76f72bd-9581-4577-88f0-6e9f7454b857.csv:Zone.Identifier
global_results_04abb547-3074-4b17-a4da-69d7e89cb218.csv:Zone.Identifier
global_results_1b7ec0c8-afb4-4c20-8230-5193f64b6612.csv
global_results_ee52092e-6949-478e-8ac0-83aa37f0f207.csv
global_results_de609f8d-5249-4a3e-8848-753c16083f3a.csv:Zone.Identifier
global_results_0cf5f4b5-5a04-4934-b715-d7b62bae6e66.csv:Zone.Identifier
global_results_2f47138c-cc83-4810-86c9-105e2333ff8d.csv
global_results_4b4ab22c-19ff-4952-9ee5-f614a3da20de.csv
global_results_23abbf06-db98-445f-9f55-fb84454ce6b9.csv:Zone.Identifier
global_results_0f3c552f-f39d-4e84-9598-83e00a379e81.csv:Zone.Identifier
global_results_73d46ae3-2f5c-4893-b77e-e34c1c23159d.csv:Zone.Identifier
global_results_f9936d4f-1e0e-47fb-ac81-1d3b619aa53d.csv:Zone.Identifier
global_results_3b2c372c-ae8b-42e3-b000-3494acb45fa6.csv
global_results_3f5f96a5-1767-46c2-bde0-5be3b96cfb0a.csv:Zone.Identifier
global_results_449887af-cd53-464a-9ae3-e0afc5a99f1e.csv
global_results_a1977de9-d50d-4945-8ae3-e681631fc8f4.csv:Zone.Identifier
global_results_03c0546a-2d28-40c1-8174-4161eb69bb53.csv
global_results_09db9e0c-159f-4e5e-a43a-19c58ab713d7.csv:Zone.Identifier
global_results_fb2ba578-ee58-43a4-825a-7dc1aef56008.csv:Zone.Identifier
global_results_ea72157d-c603-454e-a4d0-e18dbff5d5cf.csv:Zone.Identifier
global_results_528f8855-1f22-4988-92e7-9a8f253f104a.csv
global_results_1fcd9a52-3003-4e0d-a4d8-6ef22c2de376.csv:Zone.Identifier
global_results_8c3a8560-c903-4906-afdf-f024d2039ac4.csv:Zone.Identifier
global_results_fb2ba578-ee58-43a4-825a-7dc1aef56008.csv
global_results_a25b8a2b-d336-4ea9-bf95-e81040ab131f.csv:Zone.Identifier
global_results_1f2f7a5f-b040-4fb4-b8a1-915eff171adf.csv:Zone.Identifier
global_results_b175ad43-4ea7-41e0-8e4d-900fcd47a57f.csv:Zone.Identifier
global_results_4d208d81-47f5-474f-ae55-b205e8ccfff0.csv
global_results_dba5bac7-b394-4368-b76a-4b43fac04c6a.csv
global_results_a9aafff7-5a1e-4f38-a6b9-e1dad8cc6d66.csv:Zone.Identifier
global_results_ae4bede6-b7a3-40df-8032-680e998e0b55.csv:Zone.Identifier
global_results_a7958d11-3be8-4128-b608-153256651663.csv:Zone.Identifier
global_results_68c78561-ffd6-4559-9188-be8e05b6c913.csv:Zone.Identifier
global_results_6e0a4180-dc65-4c43-9937-ac4466b5c6bb.csv
global_results_2152ed9c-06ec-432a-a254-251bb06646dd.csv
global_results_84651058-c284-46ac-8ee7-8f296d38395f.csv
global_results_650371f1-98b8-4499-9469-13960b479c8b.csv
global_results_f3e61c45-d84f-4881-9240-52056c282539.csv:Zone.Identifier
global_results_8c2b2bf8-a7c4-42e7-bcfb-d073c69de5d2.csv
global_results_e4068ff6-c2a3-4202-b5b1-ca6752d5498b.csv
global_results_e2ae19a0-bed9-4156-af87-9b057dd28bee.csv:Zone.Identifier
global_results_a6712e71-b744-4c8f-b9a4-6176ecbd1c53.csv
global_results_b01b3472-f17a-45db-84ac-42afa77446b7.csv:Zone.Identifier
global_results_6fe59148-97ff-46cc-87ab-a1d3e220496d.csv
global_results_20bc2b79-b3a5-4f9d-a76e-22dab453e2a3.csv
global_results_68c78561-ffd6-4559-9188-be8e05b6c913.csv
global_results_87e6eaa8-3682-4ae6-b8f1-2c7271c85dc3.csv:Zone.Identifier
global_results_f74c5b4c-c9ea-4845-a551-e3f50d62125b.csv
global_results_e7714429-4952-4691-8b71-9f695d5a3c23.csv:Zone.Identifier
global_results_a6712e71-b744-4c8f-b9a4-6176ecbd1c53.csv:Zone.Identifier
global_results_99b29675-43a6-400e-aa87-1b0569133934.csv:Zone.Identifier
global_results_a081ba31-f754-44b9-8762-c2d88ec1e478.csv
global_results_8a61e11f-d91a-4b12-928d-d86c6956871e.csv:Zone.Identifier
global_results_9e7b4c6a-f046-4cf0-a00c-f2977e7559ee.csv
global_results_13c47666-d0bc-4307-b204-40315eb85232.csv:Zone.Identifier
global_results_93b0f375-7203-4a14-a585-d61c7c420de1.csv:Zone.Identifier
global_results_96cdbf11-ffb3-4bab-9c15-d3530cff09dc.csv
global_results_163785b0-6dab-41d5-aaed-342de76399ed.csv
global_results_f7f6ab7e-a9f9-44e7-b7d3-0b6338e3b19a.csv:Zone.Identifier
global_results_78972c86-d5fb-4e2b-b447-d6097d149757.csv:Zone.Identifier
global_results_3f3ad5f0-9cbe-4707-acb8-13cb4605ea50.csv:Zone.Identifier
global_results_e2476302-167b-4bb1-a151-1ab43424b84e.csv:Zone.Identifier
global_results_48af7093-0a52-4a82-b542-b568efb83c12.csv
global_results_03c0546a-2d28-40c1-8174-4161eb69bb53.csv:Zone.Identifier
global_results_0f5148b5-0818-48e8-847b-2a2e9c8ea75b.csv
global_results_ace25096-81e6-4ff4-8ba6-f5dcc531e569.csv:Zone.Identifier
global_results_9da61681-cebf-4d49-b9d1-b1c82c95da2f.csv
global_results_e432c52d-2fe1-420e-a37b-dfb88dee0bf1.csv:Zone.Identifier
global_results_b034b573-2e48-4fea-a064-4a3f7acdc84e.csv
global_results_38b2fac7-268a-4734-9b07-7402099885af.csv:Zone.Identifier
global_results_99b29675-43a6-400e-aa87-1b0569133934.csv
global_results_bd25c460-0b40-4972-a04e-03b767c59256.csv
global_results_a91c3272-4036-499b-a521-5c8c0a002f47.csv:Zone.Identifier
global_results_30104ce0-cebf-4c71-a154-4b858ce57214.csv:Zone.Identifier
global_results_5226db46-989a-4eba-9ec8-14b6927efcdf.csv:Zone.Identifier
global_results_0f18ceef-52b3-49e3-98dc-d09469333258.csv
global_results_1f2f7a5f-b040-4fb4-b8a1-915eff171adf.csv
global_results_9f8630c0-9985-4797-8749-8d4c6711ca8e.csv:Zone.Identifier
global_results_200577e2-8eda-4f1a-ab5f-1a9d4397e652.csv
global_results_db796356-536c-4c66-b64d-0d72e70ec17e.csv:Zone.Identifier
global_results_e2ad7534-a2ff-4373-880c-b02469ef671c.csv:Zone.Identifier
global_results_0871499d-bc9a-45fa-89c6-9f6b54607ec7.csv:Zone.Identifier
global_results_1350196e-3159-4eb3-9092-33c442c14518.csv
global_results_e7714429-4952-4691-8b71-9f695d5a3c23.csv
global_results_6fe59148-97ff-46cc-87ab-a1d3e220496d.csv:Zone.Identifier
global_results_19d504bb-2ae0-4d62-a9d1-87b64d86f857.csv
global_results_9bc5e1b5-af7b-4c76-ae44-a1e2272fee00.csv:Zone.Identifier
global_results_174156dd-495c-48c0-b3ed-5d18edd6e66e.csv

In [3]:
global_data = pd.read_csv(os.path.join(results_dir, 'global_results.csv'))

In [4]:
global_data.describe()

,Total Number of Clusters,Total Nodes Visited,Total Mission Time,Total Energy Consumption,Total Distance Covered,Average Visits per Node,Node Coverage Ratio,Mission Efficiency per Energy,Scaled Mission Efficiency per Energy (nodes per kWh),Mission Efficiency per Time,Scaled Mission Efficiency per Time (nodes per hour),Idle Ratio,Total Number of Constraints,Total Number of Variables,Computational Time,Memory Usage
count,519.000000,519.000000,519.000000,519.000000,519.000000,519.000000,519.0,519.000000,519.000000,519.000000,519.000000,519.000000,519.000000,519.000000,519.000000,519.000000
mean,13.028902,104.306358,2161.978987,22135.394456,251.400754,1.778227,1.0,0.005435,5.435131,0.056726,3.403566,1.844526,16986.514451,5094.109827,83.736610,232.550104
std,6.895044,54.456605,1418.071600,14028.446653,157.630627,0.677672,0.0,0.002042,2.042270,0.022863,1.371793,0.144444,9375.349759,2776.474256,126.906768,4.440686
min,4.000000,38.000000,440.923400,4641.497000,49.727640,1.157895,1.0,0.002407,2.407278,0.019973,1.198355,1.445385,4892.000000,1540.000000,11.806290,224.746094
25%,6.000000,38.000000,1121.333500,12200.883000,138.759640,1.215054,1.0,0.003567,3.566786,0.035422,2.125330,1.744723,7150.000000,2110.000000,23.253885,229.449219
50%,13.000000,87.000000,1849.395000,20016.521000,226.536600,1.328571,1.0,0.006737,6.736927,0.074002,4.440105,1.838341,17810.000000,5172.000000,53.003901,231.960938
75%,20.000000,140.000000,2476.436000,27609.025000,313.952600,2.114286,1.0,0.007032,7.031702,0.076505,4.590287,1.972276,25130.000000,7752.000000,83.723590,236.175781
max,27.000000,186.000000,6043.183600,57591.430000,648.797800,3.100000,1.0,0.008187,8.187014,0.086183,5.170966,2.101192,36140.000000,10734.000000,922.148441,239.703125

In [5]:
global_data.shape

(519, 19)

In [7]:
global_data

,Scenario,Objective Function,Total Number of Clusters,Total Nodes Visited,Visits per Node,Total Mission Time,Total Energy Consumption,Total Distance Covered,Average Visits per Node,Node Coverage Ratio,Mission Efficiency per Energy,Scaled Mission Efficiency per Energy (nodes per kWh),Mission Efficiency per Time,Scaled Mission Efficiency per Time (nodes per hour),Idle Ratio,Total Number of Constraints,Total Number of Variables,Computational Time,Memory Usage
0,cooperative,energy,16,140,"{116: 1, 13: 1, 67: 1, 36: 1, 117: 24, 73: 1, ...",1840.98390,19810.0410,223.77763,1.328571,1.0,0.007067,7.067123,0.076046,4.562778,1.966340,27140,8068,114.783701,235.542969
1,cooperative,coverage,9,87,"{9: 1, 8: 1, 63: 1, 15: 1, 40: 1, 42: 10, 47: ...",1160.06250,12360.3410,143.88481,1.183908,1.0,0.007039,7.038641,0.074996,4.499757,1.905070,13516,3851,29.024993,231.183594
2,cooperative,energy,9,87,"{63: 1, 69: 1, 15: 1, 43: 1, 40: 1, 9: 1, 42: ...",1139.87900,12736.0100,144.15068,1.183908,1.0,0.006831,6.831025,0.076324,4.579433,2.000212,13516,3851,38.174949,230.945312
3,individual,energy,27,186,"{76: 1, 143: 2, 138: 2, 94: 2, 57: 2, 55: 2, 0...",5250.94800,51940.5160,581.40280,2.123656,1.0,0.003581,3.581020,0.035422,2.125330,1.755873,25130,7752,556.107190,238.382812
4,individual,coverage,13,87,"{7: 1, 64: 2, 1: 2, 10: 2, 74: 2, 80: 2, 42: 1...",2322.87900,23911.7090,276.35968,2.103448,1.0,0.003638,3.638385,0.037454,2.247212,1.829626,11816,3657,39.841831,231.027344
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514,individual,energy,20,140,"{29: 3, 54: 1, 102: 3, 39: 3, 14: 3, 131: 3, 2...",6043.18360,57588.3440,648.75400,3.100000,1.0,0.002431,2.431048,0.023167,1.389996,1.686197,24303,7754,179.267523,236.500000
515,individual,energy,20,140,"{29: 3, 54: 1, 102: 3, 39: 3, 14: 3, 131: 3, 2...",6030.38500,57405.2030,646.15704,3.100000,1.0,0.002439,2.438803,0.023216,1.392946,1.684801,24303,7754,79.516000,237.238281
516,individual,coverage,13,87,"{7: 1, 64: 2, 74: 2, 1: 2, 10: 2, 80: 2, 42: 1...",2393.14010,23534.1070,263.11868,2.103448,1.0,0.003697,3.696762,0.036354,2.181235,1.742481,11816,3657,38.310402,231.464844
517,individual,coverage,6,38,"{21: 1, 17: 2, 11: 2, 6: 2, 0: 2, 28: 2, 1: 2,...",1090.65090,9914.8730,115.77373,2.052632,1.0,0.003833,3.832626,0.034842,2.090495,1.604546,4892,1540,17.024838,228.562500
518,cooperative,coverage,4,38,"{17: 1, 11: 1, 21: 1, 0: 1, 15: 1, 35: 4, 13: ...",495.48035,4795.5684,59.10796,1.157895,1.0,0.007924,7.923982,0.076693,4.601595,1.735689,5680,1632,11.867242,229.898438

In [8]:
global_data.columns

Index(['Scenario', 'Objective Function', 'Total Number of Clusters',
       'Total Nodes Visited', 'Visits per Node', 'Total Mission Time',
       'Total Energy Consumption', 'Total Distance Covered',
       'Average Visits per Node', 'Node Coverage Ratio',
       'Mission Efficiency per Energy',
       'Scaled Mission Efficiency per Energy (nodes per kWh)',
       'Mission Efficiency per Time',
       'Scaled Mission Efficiency per Time (nodes per hour)', 'Idle Ratio',
       'Total Number of Constraints', 'Total Number of Variables',
       'Computational Time', 'Memory Usage'],
      dtype='object')